name: Test

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Checkout code
        uses: actions/checkout@v3

      - run: npm i -g pnpm
      - run: pnpm install

      - run: pnpm run compile

      - run: pnpm test

      - uses: codecov/codecov-action@v3
