name: Test

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          check-latest: true

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - run: yarn compile

      - run: yarn test
