name: Test

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 17

      - name: Checkout code
        uses: actions/checkout@v2

      - run: npm i -g pnpm
      - run: pnpm install

      - run: pnpm run compile

      - run: pnpm test
